// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmHnETHbxEhAvln-kixf8xr1QZDpmqCeU',
    appId: '1:235736394673:web:12b49c2ed2fd58bf11ab90',
    messagingSenderId: '235736394673',
    projectId: 'lexiga-2b637',
    authDomain: 'lexiga-2b637.firebaseapp.com',
    storageBucket: 'lexiga-2b637.firebasestorage.app',
    measurementId: 'G-YZR0J3X9Y9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDv_3iQn-cSba5ORTY_H9HoFZRq7YCRuhQ',
    appId: '1:235736394673:android:b5f459aa7ce0049211ab90',
    messagingSenderId: '235736394673',
    projectId: 'lexiga-2b637',
    storageBucket: 'lexiga-2b637.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgZuWa4Sq6sdFgyFDTgwO0FiEW6wI9nck',
    appId: '1:235736394673:ios:af24554dfb56130b11ab90',
    messagingSenderId: '235736394673',
    projectId: 'lexiga-2b637',
    storageBucket: 'lexiga-2b637.firebasestorage.app',
    iosBundleId: 'com.example.aprendeLexico',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgZuWa4Sq6sdFgyFDTgwO0FiEW6wI9nck',
    appId: '1:235736394673:ios:af24554dfb56130b11ab90',
    messagingSenderId: '235736394673',
    projectId: 'lexiga-2b637',
    storageBucket: 'lexiga-2b637.firebasestorage.app',
    iosBundleId: 'com.example.aprendeLexico',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCmHnETHbxEhAvln-kixf8xr1QZDpmqCeU',
    appId: '1:235736394673:web:879a33e5c6634eb011ab90',
    messagingSenderId: '235736394673',
    projectId: 'lexiga-2b637',
    authDomain: 'lexiga-2b637.firebaseapp.com',
    storageBucket: 'lexiga-2b637.firebasestorage.app',
    measurementId: 'G-FXJ06RFLYW',
  );
}
